version: '3.8'

services:
  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/connect-crm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=D3v@2023
      - SPRING_CACHE_TYPE=redis
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_DATA_REDIS_HOST=redis # Aqui o host deve ser o nome do serviço 'redis'
      - SPRING_DATA_REDIS_PORT=6379

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
